version: 2

models:
  - name: customers
    description: customers target table
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: stg_customers
    description: pulling from raw customers data
    columns:
      - name: customer_id
        description: customersID column, unique and not null
        tests:
          - unique
          - not_null

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
  - name: orders
    columns:
      - name: customer_id
        tests:
          - not_null
      - name: order_id
        tests:
          - unique
          - not_null
